FROM node:24 as build-next

WORKDIR /app
COPY client/package.json client/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY client .
ENV NEXT_TELEMETRY_DISABLED=1
RUN yarn run build

FROM nginx:1.27.5
RUN mv /usr/share/nginx/html /usr/share/nginx/html-old
COPY --from=build-next /app/out /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
