FROM node:22.15.1

WORKDIR /app
COPY client/package.json client/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY client .
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
CMD ["yarn", "dev"]