# Generated by Django 4.1.3 on 2024-02-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_is_active_users_is_superuser_and_more'),
    ]

    operations = [
    ]
