# Generated by Django 4.2.10 on 2024-03-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_records_work_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_name']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterModelOptions(
            name='workpackage',
            options={'ordering': ['work_package_name']},
        ),
    ]
