# Generated by Django 5.0.4 on 2024-04-21 14:18

from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal


def create_group(apps, group_name: str, perm_names: list[str]):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group = Group.objects.create(name=group_name)
    perms = Permission.objects.filter(codename__in=perm_names).values_list("id", flat=True)
    group.permissions.add(*perms)
    group.save()


def apply_groups_creation(apps, _):
    # Probably a bit hackish
    emit_post_migrate_signal(2, False, "default")

    create_group(
        apps,
        "time_admin",
        [
            "add_asset",
            "change_asset",
            "delete_asset",
            "view_asset",
            "add_department",
            "change_department",
            "delete_department",
            "view_department",
            "add_project",
            "change_project",
            "delete_project",
            "view_project",
            "add_record",
            "change_record",
            "delete_record",
            "view_record",
            "add_team",
            "change_team",
            "delete_team",
            "view_team",
            "add_user",
            "change_user",
            "delete_user",
            "view_user",
            "add_workpackage",
            "change_workpackage",
            "delete_workpackage",
            "view_workpackage",
        ],
    )

    create_group(
        apps,
        "time_user",
        [
            "view_asset",
            "view_department",
            "view_project",
            "add_record",
            "change_record",
            "delete_record",
            "view_record",
            "view_team",
            "view_user",
            "view_workpackage",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_groups_user_user_permissions"),
        ("auth", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_groups_creation, migrations.RunPython.noop)]
