# Generated by Django 5.0.4 on 2024-04-21 16:04

from django.db import migrations


def make_users_time_users(apps, _):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("api", "User")

    time_user = Group.objects.get(name="time_user")

    for user in User.objects.all():
        user.groups.add(time_user)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_auto_20240421_1418"),
    ]

    operations = [migrations.RunPython(make_users_time_users, migrations.RunPython.noop)]
