# Generated by Django 4.2.21 on 2025-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on-hold', 'On Hold')], default='active', max_length=50),
        ),
    ]
