# Generated by Django 5.2.1 on 2025-05-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_workpackage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authorized_teams',
            field=models.ManyToManyField(blank=True, help_text='Teams whose members have access to this project.', related_name='accessible_projects_team', to='api.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have explicit access to this project.', related_name='accessible_projects_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_all_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
