# Generated by Django 4.2.21 on 2025-06-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_authorized_teams_project_authorized_users_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user_id', 'project_id', '-id'], name='records_user_id_286cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user_id', '-id'], name='records_user_id_36bc90_idx'),
        ),
    ]
