# Generated by Django 4.2.21 on 2025-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_record_records_user_id_286cd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
