worker_processes 4;

events {
    worker_connections 1024;
}

http {
    upstream time-recorder-server {
        server time-recorder-server:8000;
    }

    server {
        listen 80;
        root  /usr/share/nginx/html;
        include /etc/nginx/mime.types;

        # route all other requests to the index for react router
        location / {
            try_files $uri /index.html;
        }

        location ~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location /api {
            proxy_pass http://time-recorder-server;
            proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection 'upgrade';
			proxy_set_header Host $host;
			proxy_cache_bypass $http_upgrade;
        }

        location /admin {
            proxy_pass http://time-recorder-server;
            proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection 'upgrade';
			proxy_set_header Host $host;
			proxy_cache_bypass $http_upgrade;
        }

        location /static/ {
            alias /app/static/;
        }
    }
}
